theme: jekyll-theme-slate
title: %NAME%
description: %DESCRIPTION%
copyright: %COPYRIGHT%
version: %VERSION%
github:
  repository_url: https://github.com/MOEAFramework/MOEAFramework
google_analytics: G-G5Q9J52Z1T