theme: jekyll-theme-slate
title: %name%
description: %description%
github:
  repository_url: %repository%
google_analytics: G-G5Q9J52Z1T
carousel:
  - image: assets/images/diagnosticTool.png
  - image: assets/images/runtimeViewer.png
  - image: assets/images/tsp.png
  - image: assets/images/symbolicRegression.png