name: Tests

on: [push]

jobs:
  ant-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '11', '16', '17', '18', '19' ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java }}
        distribution: zulu
    - name: Setup up JUnit 4
      run: |
        cd lib
        wget https://search.maven.org/remotecontent?filepath=junit/junit/4.13.2/junit-4.13.2.jar
        wget https://search.maven.org/remotecontent?filepath=org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
    - name: Test with Ant - Java ${{ matrix.java }}
      run: ant -DON_CI=true -f test.xml
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: ant-test-results-${{ matrix.java }}
        path: test-results

  maven-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: temurin
        cache: maven
    - name: Prepare Maven project - Java ${{ matrix.java }}
      run: ant -f test.xml build-maven-tests
    - name: Run Maven tests - Java ${{ matrix.java }}
      run: |
        cd build
        mvn test
      env:
        ON_CI: true
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: maven-test-results-${{ matrix.java }}
        path: build/target/surefire-reports

  package-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: temurin
    - name: Package binary
      run: ant -f build.xml package-binary
    - name: Package source
      run: ant -f build.xml package-source
    - name: Package maven
      run: ant -f build.xml package-maven
    - name: Package demo
      run: ant -f build.xml package-demo
    - name: Package website
      run: ant -f build.xml package-website
