name: Validate and stage release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version to publish
        required: true
      publish-website:
        description: 'Create draft Website release'
        default: true
        type: boolean 
      publish-github:
        description: 'Create draft GitHub release'
        default: true
        type: boolean
      publish-maven:
        description: 'Create Maven release'
        default: true
        type: boolean
      trigger-tests:
        description: 'Trigger integration tests'
        default: true
        type: boolean
      skip-validation:
        description: 'Skip version validations'
        default: false
        type: boolean

jobs:
  stage:
    runs-on: ubuntu-latest
    steps:
      - name: Setup release
        uses: MOEAFramework/.github/actions/setup-build@main
        with:
          setup-git: true
          email: ${{ secrets.EMAIL }}
          username: ${{ secrets.USERNAME }}
          github-token: ${{ secrets.PAT }}
          gpg-signing-key: ${{ secrets.GPG_SIGNING_KEY }}
      - name: Get project info
        uses: MOEAFramework/.github/actions/get-project-info@main
        with:
          expected-version: ${{ inputs.version }}
          skip-validation: ${{ inputs.skip-validation }}
      - name: Build release artifacts
        if: ${{ inputs.publish-github && ! endsWith('-SNAPSHOT') }}
        uses: MOEAFramework/.github/actions/run-ant@main
        with:
          target: package-binary package-demo package-source
      - name: Stage GitHub release
        if: ${{ inputs.publish-github && ! endsWith('-SNAPSHOT') }}
        uses: MOEAFramework/.github/actions/publish-github@main
        with:
          release-notes-file: docs/releaseNotes.md
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Maven project
        if: ${{ inputs.publish-maven }}
        uses: MOEAFramework/.github/actions/run-ant@main
        with:
          target: build-maven
      - name: Build and stage Maven artifacts
        if: ${{ inputs.publish-maven }}
        uses: MOEAFramework/.github/actions/publish-maven@main
        with:
          directory: build
          skip-tests: true
          ossrh-username: ${{ secrets.OSSRH_USERNAME }}
          ossrh-password: ${{ secrets.OSSRH_TOKEN }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Setup website
        if: ${{ inputs.publish-website && ! endsWith('-SNAPSHOT') }}
        uses: MOEAFramework/.github/actions/run-ant@main
        with:
          target: package-website
      - name: Stage website
        if: ${{ inputs.publish-website && ! endsWith('-SNAPSHOT') }}
        uses: MOEAFramework/.github/actions/sync-repo@main
        with:
          directory: ../MOEAFramework/build/
          repository: Website
          branch-name: v${{ env.BUILD_VERSION }}
          message: Update for v${{ env.BUILD_VERSION }}
          github-token: ${{ secrets.PAT }}
      - name: Trigger integration tests
        if: ${{ inputs.trigger-tests && ! endsWith('-SNAPSHOT') }}
        uses: MOEAFramework/.github/actions/integration-test@main
        with:
          github-token: ${{ secrets.PAT }}
